#ifndef  V8_FRAME_H
#define  V8_FRAME_H



#include "htmlElement.h"





class Frame:public HTMLElement{
public:
   Frame(xmlNodePtr node);
   virtual ~Frame();
public:
   v8::Handle<v8::ObjectTemplate> embed();
public:

//   static Handle<Value> GetProperty(Local<String> property,const AccessorInfo &info);
//   static void SetProperty(Local<String> property, Local<Value> value,const AccessorInfo& info);
public:
DECLARE_STATIC_ATTRNAME(align,align)//Sets or returns the value of the align attribute in an iframe 	Yes
DECLARE_STATIC_ATTRNAME(contentDocument,contentDocument)//Returns the document object generated by a frame/iframe 	Yes
DECLARE_STATIC_ATTRNAME(contentWindow,contentWindow)//Returns the window object generated by a frame/iframe 	No
DECLARE_STATIC_ATTRNAME(frameBorder,frameBorder)//Sets or returns the value of the frameborder attribute in a frame/iframe 	Yes
DECLARE_STATIC_ATTRNAME(height,height)//Sets or returns the value of the height attribute in an iframe 	Yes
DECLARE_STATIC_ATTRNAME(longDesc,longDesc)//Sets or returns the value of the longdesc attribute in a frame/iframe 	Yes
DECLARE_STATIC_ATTRNAME(marginHeight,marginHeight)//Sets or returns the value of the marginheight attribute in a frame/iframe 	Yes
DECLARE_STATIC_ATTRNAME(marginWidth,marginWidth)//Sets or returns the value of the marginwidth attribute in a frame/iframe 	Yes
DECLARE_STATIC_ATTRNAME(name,name)//Sets or returns the value of the name attribute in a frame/iframe 	Yes
DECLARE_STATIC_ATTRNAME(noResize,noResize)//Sets or returns the value of the noresize attribute in a frame 	Yes
DECLARE_STATIC_ATTRNAME(scrolling,scrolling)//Sets or returns the value of the scrolling attribute in a frame/iframe 	Yes
DECLARE_STATIC_ATTRNAME(src,src)//Sets or returns the value of the src attribute in a frame/iframe 	Yes
DECLARE_STATIC_ATTRNAME(width,width)//Sets or returns the value of the width attribute in an iframe 	Yes
};
#endif
